/*
 *  RapidMiner
 *
 *  Copyright (C) 2001-2007 by Rapid-I and the contributors
 *
 *  Complete list of developers available at our web site:
 *
 *       http://rapid-i.com
 *
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License as 
 *  published by the Free Software Foundation; either version 2 of the
 *  License, or (at your option) any later version. 
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 *  USA.
 */
package com.rapidminer.operator.learner.weka;

import com.rapidminer.operator.ResultObjectAdapter;

import weka.associations.Associator;

/**
 * In contrast to models generated by normal learners, the association rules
 * cannot be applied to an example set. Hence, there is no way to evaluate the
 * performance of association rules yet.
 * 
 * @author Ingo Mierswa, Simon Fischer
 * @version $Id: WekaAssociator.java,v 1.1 2007/05/27 21:59:01 ingomierswa Exp $
 */
public class WekaAssociator extends ResultObjectAdapter {

	private static final long serialVersionUID = 5270922650382578487L;

	private Associator associator;

	private String name;

	public WekaAssociator(String name, Associator associator) {
		this.name = name;
		this.associator = associator;
	}

	public String getName() {
		return name;
	}

	public String toString() {
		return associator.toString();
	}
    
    public String getExtension() { return "ass"; }
    
    public String getFileDescription() { return "association rules"; }
    
}
